name: go-test
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: gosmig
          POSTGRES_USER: gosmig
          POSTGRES_PASSWORD: gosmig
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GOFLAGS: -buildvcs=false

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'

      - name: Check that Go modules are tidy
        uses: katexochen/go-tidy-check@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Check for vulnerabilities
        uses: golang/govulncheck-action@v1

      - name: Build
        run: make build-only

      - name: Test with coverage
        run: make test-coverage

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

